# Generated by Django 3.1.5 on 2021-01-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210120_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_URL',
            field=models.CharField(max_length=200),
        ),
    ]
